### ISSUE TITLE
Typing plain 'mothership' should give a list of commands

### ISSUE THREAD

**Issue by bharatagarwal** [unnamed-paas/mothership-cli#5]
![Screenshot 2019-12-10 at 11 33 09 PM](https://user-images.githubusercontent.com/15229351/70555627-72ee6000-1ba5-11ea-948b-79568e117cd3.png)

**Comment by jkulton** [comment]
Oooh I like this.

**Comment by jkulton** [comment]
Check out #7 👍

**Comment by jkulton** [comment]
Merged #7

**Comment by bharatagarwal** [comment]
Fast as ⚡️!
